version: "3.8"

volumes:
  postgres_data:

networks:
  trust:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - trust
    env_file:
      - ./frontend/.env

  trust-api:
    build:
      context: ./server
    ports:
      - "3080:3080"
    volumes:
      - ./server:/usr/src/app
      - ./server/public:/usr/src/app/public
    networks:
      - trust
    depends_on:
      - db
    env_file:
      - ./server/.env

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    networks:
      - trust
    depends_on:
      - db
    env_file:
      - ./server/.env
